# Generated by Django 4.1.2 on 2024-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('unknown', 'Unknown')], default='sale', max_length=10),
        ),
    ]
